### ISSUE TITLE
Could you use Vundle to manage plugins?

### ISSUE THREAD

**Issue by peidong** [yangyangwithgnu/use_vim_as_ide#10]
Because Vundle is easier to manage plugin updates, maybe adding Vundle support is better.

**Comment by rundisR** [comment]
actually u can try vimplug, which is similar to vundle

however since it's possible to make vimplug/vundle work with pathogen, i suggest simply giving the github link of vimplug/vundle and allow users set them by themselves

**Comment by xushaobo** [comment]
you can see my .vimrc on https://github.com/xushaobo?tab=repositories , it use vundle based on yangyangwithgun's article.

**Comment by rundisR** [comment]
yeah, pretty good
however, i still suggest u to try vim-plug ;D

im using pathogen + vimplug

**Comment by wsdjeg** [comment]
@rundisR why do not use Neobundle,it contain all the function

**Comment by rundisR** [comment]
@wsdjeg im used to use vim plug...recommended by a friend;D

**Comment by wsdjeg** [comment]
i know ,because i need to lock to different commit and branch,so i am using the neobundle,also the plugin can compile other plugin

**Comment by rundisR** [comment]
that's ok
actually it doesn't matter which one to use, everyone has their own choice and their reason
so i suppose that we only need to focus on plugin itslef instead of management

**Comment by wsdjeg** [comment]
yes , i know maybe i use neobundle just because i meet it before vundle and plugen or other management tools!

**Comment by yangyangwithgnu** [comment]
OK, U get it, I use vundle in my article now.
