### ISSUE TITLE
关于动态调试的问题

### ISSUE THREAD

**Issue by gggscfaii** [yangyangwithgnu/use_vim_as_ide#11]
您好，按照你的文档，已经把相应的功能都已配置。请问您在工作中，是如何动态调试源码的？

**Comment by peidong** [comment]
你是在linux配置的吗?

**Comment by gggscfaii** [comment]
@peidong   是在mac中 配置

**Comment by peidong** [comment]
@gggscfaii 你用的是macvim吗? 是.gvimrc还是在.vimrc配置的?

**Comment by gggscfaii** [comment]
@peidong 直接用这个项目中的.vimrc文件

**Comment by peidong** [comment]
@gggscfaii 是系统自带的vim,还是装的macvim?

**Comment by nezhazheng** [comment]
debug是ide不可或缺的一部分，强烈建议把这一部分补上。

**Comment by yangyangwithgnu** [comment]
单独用 gdb 进行源码调试的习惯在我心中早已根深蒂固，虽然很多次说服自己改在 vim 调整，但是一直驱动力不强。容我再想想  ( ﾟДﾟ)σ

**Comment by xushaobo** [comment]
感觉cgdb高亮比gdb好点，不过不知道为什么跑不起来程序，gdb就可以
