### ISSUE TITLE
About <Leader> shortcuts

### ISSUE THREAD

**Issue by TossShinHwa** [yangyangwithgnu/use_vim_as_ide#12]
文中提到:

```
" 定义快捷键的前缀，即<Leader>
let mapleader=";"
```

如果把`<Leader>`定义成了分号, 那么 `f{char}` 的时候又怎么到下一次匹配呢? 因为这个的默认快捷键就是 `;`

**Comment by yangyangwithgnu** [comment]
详细描述下，不明白你“f{char} 的时候又怎么到下一次匹配”。

**Comment by TossShinHwa** [comment]
例:

```
'Hello World'
```

我可以先按 `fo`, 这样会定位到第一个` o`, 然后继续按 `fo` 就能定位到第二个 `o`. 但是我也可以直接按 `;`, 他能直接执行上一次 f{char} 的操作. (同样, 我可以按`,` 来向后退. 实际上 `;`和`,`就是上一个下一个的意思, 这里很类似`/`的搜索功能.)

这个和使用`.`来执行上一次的命令块也很类似的. 只是`.`是重复命令, `;`是重复搜索.

所以如果你使用这个作为< Leader>, 那么这个特性将失效.

**Comment by yangyangwithgnu** [comment]
嗯，这就看你如何取舍了。
