### ISSUE TITLE
请问如何安装预先安装相关依赖库的头文件

### ISSUE THREAD

**Issue by xsh6528** [yangyangwithgnu/use_vim_as_ide#14]
"预先安装相关依赖库的头文件，python-devel、python3-devel、ruby-devel、libX11-devel、gtk-devel、gtk2-devel、gtk3-devel、ncurses-devel"

谷歌了一下没有很理想的答案

**Comment by Leonard-Xie** [comment]
没明白你的意思。

Leonard

**Comment by ZhangJingrong** [comment]
如果是需要用到相应的依赖库，应该需要安装dev库吧。
 比如在ubuntu里面 sudo apt-get install python-dev

**Comment by Leonard-Xie** [comment]
是的

Leonard
