### ISSUE TITLE
UltiSnips结对符使Vim的缩进不正确要怎么办？ 

### ISSUE THREAD

**Issue by Inori** [yangyangwithgnu/use_vim_as_ide#17]
比如当打完一个函数或者一行 ```if()``` 语句时，回车，光标在下一行：
![rtx](https://cloud.githubusercontent.com/assets/6732524/10409939/9eb1bf26-6f64-11e5-8910-f6f072e6941a.png)

这时如果正常输入```{```，Vim能够正常缩进：
![rtx 1](https://cloud.githubusercontent.com/assets/6732524/10409940/9fe66540-6f64-11e5-91a5-e6c12061b866.png)

如果使用文中的snippets
```
# 大括号 brace 
snippet br "brace" i 
{
    ${1}
}${2}
endsnippet
```
输入```br<leader><tab>```，Vim就认不出```{```，使缩进不正确:
![rtx 2](https://cloud.githubusercontent.com/assets/6732524/10409941/a15ee23a-6f64-11e5-8489-696967d6665f.png)

不知道除了把快捷键设成```{```以外有没有其它更好的方法？

**Comment by rundisR** [comment]
更好的-方法是不通过snippets实现括号补全-。-
有其他插件你可以看看，譬如spf13用的autoclose，或者我用的delimitmate

**Comment by yangyangwithgnu** [comment]
这与各人的编码风格有关。关于 if 语句，不关 if 体内有几条语句，哪怕只有一条，我都会加上 {}，并且开大括号与 if 同行，如下：
```
if (/* condition */) {
    TODO
}
```
再结合 UltiSnips（https://github.com/SirVer/ultisnips ）已模版方式快捷输入 if 框架，所以，基本上不会遇到你说的问题。

如果按你的方式，可以将整个 {} 选中后键入 =，让其格式化。
