### ISSUE TITLE
跳转行首和行尾的键盘映射导致x键删除字符错位

### ISSUE THREAD

**Issue by DarryO** [yangyangwithgnu/use_vim_as_ide#19]
当添加nmap lb 0 或nmap le $后，会导致使用 l 移动光标，再使用x删除字符错位。x将删除光标后一个字符，而不是当前的字符。

vim 7.4.52， 当.vimrc文件中仅仅只存在这两条映射时仍然是这样。

**Comment by xushaobo** [comment]
是的

在 2015年11月4日 下午9:08，LH <notifications@github.com>写道：

**Comment by xushaobo** [comment]
换别的不就好了

在 2015年11月4日 下午9:09，ihcy it <xushaobo333@gmail.com>写道：

**Comment by DarryO** [comment]
是的，换别的就好了。只是我觉得在文章里说明下比较好，一开始遇到还是很迷惑的。

**Comment by yangyangwithgnu** [comment]
光标快速移至行首的快捷键 lh 与光标右移键 l 的确有一定冲突，目前看表现形式有两种，一是你反应的 vim 收到 l 后立即执行光标右移操作，并未等待同样有 l 的移至行首的 lh；一是键入 l 后 vim 等待是否为 lh，导致光标左移操作延迟。现添加 <Leader> 规避该问题。

```
" 定义快捷键到行首和行尾
nmap <Leader>lb 0
nmap <Leader>le $
```

**Comment by neoisok** [comment]
lb 和 le 是键盘上的哪个键？
