### ISSUE TITLE
color sheme mass up

### ISSUE THREAD

**Issue by DeathPoem** [yangyangwithgnu/use_vim_as_ide#22]
![image](https://cloud.githubusercontent.com/assets/13230384/12009507/31cee8e6-acb5-11e5-8183-7b4fc88d5b24.png)

I just try to apply your article, but this colorsheme seams bad working for my vim, rest of stuffs works as expected. 
Can it be a trouble if I got this vim from apt-get? Since there are many other .vim files in this directory:/usr/share

**Comment by rundisR** [comment]
this is because that what you opened is vim, not gvim. so the color scheme messed up. try use gvim.

**Comment by DeathPoem** [comment]
@rundisR not that case, I just set the color-type to 256 in .vimrc. And that problem is solved. By the way, thank you for your article, that's helpful. But MY youcompleteme is not working so cool as your demo shows. This trouble has tangled me for a few days to make me crying out of my tears. Do you know there is anyway to make YCM to complete my function prototype for the full entity not only the function name? (Like this:FILE fopen(*char filename)) 
The most awesome plugin I want is YCM, and it seems quite overwhelming for me.

**Comment by rundisR** [comment]
@DeathPoem actually it is the problem... the problem of color type only appear when you use vim via your terminal, so the easiest way to solve it is to use gvim. by the way, why not use gvim? since you are already using the gui... 
vim under terminal is used when you are under the condition without gui such as ssh

**Comment by DeathPoem** [comment]
@rundisR I just want myself get used of it, and I don't figure out big difference between them. Thank you for your suggestion and may I persist.
 A word out of the business, I came from Chengdu. : )

**Comment by yangyangwithgnu** [comment]
@DeathPoem 

YCM 老版适配是有很多问题，大部份是 libclang 版本过低以及 .ycm_extra_conf.py 配置文件，其中，.ycm_extra_conf.py 导致补全是最大可能，所以，我把直接的 .ycm_extra_conf.py 已经放在本项目中，你可以下载后再试试，特别注意：
```
flags = [ 
    '-std=c++11', 
    '-O0', 
    '-Werror', 
    '-Weverything', 
    '-Wno-documentation', 
    '-Wno-deprecated-declarations', 
    '-Wno-disabled-macro-expansion', 
    '-Wno-float-equal', 
    '-Wno-c++98-compat', 
    '-Wno-c++98-compat-pedantic', 
    '-Wno-global-constructors', 
    '-Wno-exit-time-destructors', 
    '-Wno-missing-prototypes', 
    '-Wno-padded', 
    '-Wno-old-style-cast',
    '-Wno-weak-vtables',
    '-x', 
    'c++', 
    '-I', 
    '.', 
    '-isystem', 
    '/usr/include/', 
] 
```
