### ISSUE TITLE
第一张图的Terminal是哪个？

### ISSUE THREAD

**Issue by nasacj** [yangyangwithgnu/use_vim_as_ide#23]
<div align="center">
<img src="https://github.com/yangyangwithgnu/use_vim_as_ide/blob/master/pics/%E5%9B%BE%E5%BD%A2%E7%8E%AF%E5%A2%83%E4%B8%8B%20IDE%20%E6%80%BB%E6%8F%BD.png" alt=""/><br />
（图形环境下 IDE 总揽）
</div>

这里的Temianl是哪个？是gVim？我在iTerm2里，折叠标志没有三角的样子，而且行号不会高亮

**Comment by yangyangwithgnu** [comment]
gvim
