### ISSUE TITLE
粘贴快捷键 是 结对符跳转快捷键 的前缀

### ISSUE THREAD

**Issue by TomatoFishs** [yangyangwithgnu/use_vim_as_ide#24]
" 设置快捷键将系统剪贴板内容粘贴至 vim
nmap <Leader>p "+p

" 定义快捷键在结对符之间跳转，助记pair
nmap <Leader>pa %

粘贴的时候觉得延迟，然后发现 粘贴快捷键 是 结对符跳转快捷键 的前缀

我自己把结对符的快捷键注释了，感觉百分号按起来还算顺手～(*^__^*) 
感谢这份教程！作者巨巨辛苦了～！

**Comment by yangyangwithgnu** [comment]
已优化：
```
" 定义快捷键在结对符之间跳转，助记pair
nmap <leader>M %
```
