### ISSUE TITLE
Fail to make ycm_support_libs

### ISSUE THREAD

**Issue by LanceGe** [yangyangwithgnu/use_vim_as_ide#25]
In file included from /home/lancelot/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/CandidateRepository.cpp:28:0:
/home/lancelot/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/ClangCompleter/CompletionData.h:23:27: fatal error: clang-c/Index.h: No such file or directory
compilation terminated.
ycm/CMakeFiles/ycm_client_support.dir/build.make:123: recipe for target 'ycm/CMakeFiles/ycm_client_support.dir/CandidateRepository.cpp.o' failed
make[3]: *** [ycm/CMakeFiles/ycm_client_support.dir/CandidateRepository.cpp.o] Error 1
CMakeFiles/Makefile2:130: recipe for target 'ycm/CMakeFiles/ycm_client_support.dir/all' failed
make[2]: *** [ycm/CMakeFiles/ycm_client_support.dir/all] Error 2
CMakeFiles/Makefile2:209: recipe for target 'ycm/CMakeFiles/ycm_support_libs.dir/rule' failed
make[1]: *** [ycm/CMakeFiles/ycm_support_libs.dir/rule] Error 2
Makefile:148: recipe for target 'ycm_support_libs' failed
make: *** [ycm_support_libs] Error 2

**Comment by yangyangwithgnu** [comment]
缺少 llvm-clang-devel，安装即可。
