### ISSUE TITLE
您好，我模板提示和您一样的 并且设置了 let g:UltiSnipsSnippetDirectories=["mysnippets"] 怎么没有模板提示？

### ISSUE THREAD

**Issue by hejie** [yangyangwithgnu/use_vim_as_ide#26]

**Comment by yangyangwithgnu** [comment]
确认你的模版文件是否也位于 ~/.vim/bundle/ultisnips/mysnippets/cpp.snippets

**Comment by hejie** [comment]
遇到一个问题，在模板补全这块～

我输入ife 进行补全 没用，你是输入什么结束键进行补全的，看你的gif好像是 输入分号呀，不知道我说明白了没有。。

**Comment by yangyangwithgnu** [comment]
@hejie 
YCM 没有补全键的说法。任何补全都不行？

**Comment by hejie** [comment]
有提示补全，但不知道如何显示出来，比如选中补全ife后按回车没用，或者 有别方式像IDE一样选中后按回车或者快捷键显示出来？

**Comment by hejie** [comment]
我看你的gif 是选择补全后 按什么键把它显示到vim上的？
一般的IDE是选中补全后回车就显示出来了

**Comment by hejie** [comment]
知道了哈，谢谢啦
