### ISSUE TITLE
如果缺失，源码构建过程虽不会报错，但最终生成的 vim 很可能缺失某些功能。。。

### ISSUE THREAD

**Issue by hejie** [yangyangwithgnu/use_vim_as_ide#27]
这里能给出相应的安装地址和说明？ 先谢过 ，初学者很多出现问题都不知道是不是这里的原因导致

**Comment by yangyangwithgnu** [comment]
这些是 vim 源码安装时需要用到的其他库，无需指明其 URL 地址，通过包管理工具直接安装即可。各个发行套件采用的包管理工具不同（如，ubuntu 的 apt-get，openSUSE 的 zypper）、库头文件的命名规则不同（如，libcurl-dev、libcurl-devel），所以，你的根据自身情况安装。

如果是 win 用户，建议下载预编译好安装程序，可以考虑 https://github.com/vim/vim-win32-installer
