### ISSUE TITLE
安装libxxabi时报错

### ISSUE THREAD

**Issue by xushaobo** [yangyangwithgnu/use_vim_as_ide#36]
cxa_exception.o:/home/rosa/Downloads/libcxxabi/lib/../src/cxa_exception.cpp:708: first defined here
clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by BlueCatFlord** [comment]
这个问题你解决了吗？我也遇到了

**Comment by PokemonWei** [comment]
是的，我也遇到了clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)，我找到了一个解决方法，可以试试
“在链接的时候出现的，很多重定义错误。解决方法是删除/src/cxa_noexception.cpp文件。如果还是报错，检查是否存在lib/cxa_noexception.o文件，删除即可。“
——来自http://www.emhom.com/thread-416-1-1.html
@BlueCatFlord
