### ISSUE TITLE
这东西很赞,关于快捷键问题!

### ISSUE THREAD

**Issue by chzhuo** [yangyangwithgnu/use_vim_as_ide#40]
我看到你的文档中定义了很多快捷键,  我也跟着你使用了该种快捷键. 我想问问这个快捷键是不是国际通用的呀?  以后使用别人的vim不方便呀!

**Comment by fcymk2** [comment]
快捷键哪有什么通用的....怎么顺手怎么来...

**Comment by tao12345666333** [comment]
只有原生的才是通用的。。 （所以如果想到处通用， 可能你最好是学会默认自带的快捷键或者命令

**Comment by chzhuo** [comment]
哦哦哦，了解！目前已经入目，最近在学vimscript，问问各位大神，有没有好的中文教程呀？

**Comment by tao12345666333** [comment]
@chzhuo  貌似没有， 建议还是直接看文档来的快也比较准

**Comment by yangyangwithgnu** [comment]
《Learn Vimscript the Hard Way》、《Scripting the Vim editor》、vim-tutorial-self 都不错，中文版不清楚。另，一般环境下的 vim 都是带 python 构建的，用 python 写扩展更方便、高效。vimscript 除了环境普适性好些外，没啥优势。
