### ISSUE TITLE
Ubuntu tty vim color

### ISSUE THREAD

**Issue by kangqf** [yangyangwithgnu/use_vim_as_ide#6]
当我使用Ctrl+Alt+Fn换到字符界面时发现配色全没了，全是些淡蓝色？？？？用的Ubuntu系统，还有楼主的插件管理为什么不使用Vundle？

**Comment by yangyangwithgnu** [comment]
当我使用Ctrl+Alt+Fn换到字符界面时发现配色全没了，全是些淡蓝色？？？？
—— 纯字符模式必须安装 fbterm

用的Ubuntu系统，还有楼主的插件管理为什么不使用Vundle
—— 好吧，你是第 32 个让我用 vundle 替换 pathogen 的人。再等等，再等等 .......

**Comment by kangqf** [comment]
好像不是这个原因，一开始就装了fbterm（为了防止中文乱码），可是在纯字符下还是vim配不上色。包括什么使用256色啊xterm那些个都试了个遍，后面发现自己的gui和Terminal都是用的molokai，但奇迹发生了当我全换solarized 时就在纯字符界面有彩色了。然后就在纯字符和Terminal里echo了一下$TERM，发现在Terminal里面是xterm在tty里面是Linux。所以就加了几句判断在tty用solarized 在Terminal用molokai 才折腾完。虽然不知道原因，但觉得是配色的问题，应该是有的主题对Ubuntu 的tty这种终端没有配vim相应的颜色，比如molokai。
