### ISSUE TITLE
申请用此教程作为SpaceVim的默认中文教程

### ISSUE THREAD

**Issue by wsdjeg** [yangyangwithgnu/use_vim_as_ide#63]
@yangyangwithgnu 

你好，我是[SpaceVim这](https://github.com/SpaceVim/SpaceVim)个项目的发起者，也申请了一个域名 https://spacevim.org ，首先简单说下SpaceVim的初衷，我挺喜欢spacemacs那种模块化的模式，所以我也想为vim来做一个这样的模块化的配置，这一项目目的不是打造一个功能非常强大的IDE，相反，最终是想做一个最简单华的框架。主要的开发精力应该是在各个模块的开发和完善，用户根据自己的自身需要，载入相应的模块，将SpaceVim打造成自己的IDE。

目前这个项目，国外的支持用户相对多一点，国内确认也是因为没有很好的平台，此外确实是因为我还没有为这个项目写中文的介绍文档。PR正在进行中。

我在英文介绍中采用vim-galore作为教程，而在中文的说明中，我想以这篇文章作为教程，也希望您可以帮助推广下SpaceVim这种模块化的思想，我也想有更多的人来提交各种layer。

wsdjeg
2017-1-21

**Comment by yangyangwithgnu** [comment]
这篇教程你随意使用，兄弟。后续找时间再在文章中增加 SpaceVim 的介绍。
