### ISSUE TITLE
Do you use Ubuntu?

### ISSUE THREAD

**Issue by xinqiu** [yangyangwithgnu/use_vim_as_ide#8]
您好，请问，您是用的Ubuntu配GVim么？

**Comment by yangyangwithgnu** [comment]
openSUSE 13.2，https://github.com/yangyangwithgnu/the_new_world_linux 。不过，这个版本有多处 bug，比如，NetworkManager、待机、垃圾桶等等。在给 openSUSE 最后一个版本的机会，若下个版本仍让我不满意，kali 或者 LFS 将会是考虑之一。

**Comment by magiczhj** [comment]
不是 我是在server上用vim

发自我的 iPhone
