### ISSUE TITLE
unbuntu16.04无法定位软件python-devel等

### ISSUE THREAD

**Issue by JoeQueenneu** [yangyangwithgnu/use_vim_as_ide#87]
如题，无法安装python-devel、python3-devel、ruby-devel、lua-devel等等，换了清华源、阿里源等，也执行sudo  apt-get update/upgrade都没有效果，请问各位大神这是什么原因？

**Comment by alexromance** [comment]
这个是你软件名字写的不对，ubuntu的头文件一般都是libxxx-dev ，你需要用sudo apt search xxx-dev 来手动搜索，然后sudo apt install libxxx-dev即可
