### ISSUE TITLE
是否能在标题上加一个副标题 for win c/c++

### ISSUE THREAD

**Issue by morefreeze** [yangyangwithgnu/use_vim_as_ide#9]
从文可以看到作者更偏向MS方向的c，pragram once应该是只有MS才有的命令吧。
感谢作者的劳动，我已经从头到尾读完。

**Comment by yangyangwithgnu** [comment]
客气。基本上，你说的几点，我回答都是否定的。

0）开篇我已强调“希望将 vim 打造成 C/C++ 语言的 IDE，而非其他语言”；

1）我通常只写原生 unix-like 程序，开发环境也在 linux 下，用 cygwin 进行 windows 程序移植；

2）
```
#pragma once
```
虽暂未纳入 C++ 标准，但绝对不是 cl （M$ 的编译器）独有的，由于这种写法广泛存在，所以，GCC、clang、intel C++ 等等常见编译器早已支持。个人觉得这种写法比宏优雅，当然，你说的可移植性，是可以理解的。
